version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-shortening} # Correct DB name
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-alex} # Correct password
      POSTGRES_USER: ${POSTGRES_USER:-alexandre} # Correct user
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-shortening}", "-U", "${POSTGRES_USER:-alexandre}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}&charset=utf8"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  database_data:
